[link](https://apps.skillfactory.ru/learning/course/course-v1:SkillFactory+DST-3.0+28FEB2021/block-v1:SkillFactory+DST-3.0+28FEB2021+type@sequential+block@548c7778fc5f4fde88d685d5f0497973/block-v1:SkillFactory+DST-3.0+28FEB2021+type@vertical+block@7daa0bbf8b5843399d242afef2552a06)

Нормирование вектора — это получение вектора с тем же направлением, что и исходный, но с нормой 1.

Норма вектора вычисляется как корень из суммы квадратов его компонент. Её физический смысл: норма показывает, насколько вектор «большой».

Длина вектора (в физическом смысле) — это то же, что и норма, применимо к векторам в реальном пространстве.

Нормирование производится делением вектора на его норму.

In [2]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

display(Hut_Paradise_DF)

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [5]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[5]

array([50, 44,  2, 13, 12, 35], dtype=int64)

3.4 Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:

5,12,10,3,6,13,8,21,5

In [6]:
print(Hut_Paradise_values[:,3])

[ 5 12 10  3  6 13  8 21  5]


3.5 Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [7]:
print(Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5])

[13 12 15 13 17  9 20 15 25]


3.6 Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [9]:
import numpy as np

time=np.array([10,20,30,15,5,40,20,8,20])
print(Hut_Paradise_values[:,4] @ time)

1348


Дано три вектора:

u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

3.7 Составьте линейную комбинацию векторов v и m с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [11]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])


c=2*v-3*w
print(c)

[-3 14  3  4  2]


In [12]:
if c @ u == 0:
    print('Ортогональны')
else:
    print('Не ортогональны')

Ортогональны


СМ ноутбук по векторам первого модуля